const charCheckbox = [
  {
    id: 'charCheckbox0',
    name: 'pastMedicalHistory',
    value: 'Past Medical History',
    label: 'Past Medical History',
    class: 'check',
  },
  {
    id: 'charCheckbox1',
    name: 'medicationTaken',
    value: 'Medications taken',
    label: 'Medications taken',
    class: 'check',
  },
  {
    id: 'charCheckbox2',
    name: 'dose',
    value: 'Dose',
    label: 'Dose',
    class: 'check',
  },
  {
    id: 'charCheckbox3',
    name: 'allergies',
    value: 'Allergies',
    label: 'Allergies',
    class: 'check',
  },
  {
    id: 'charCheckbox4',
    name: 'birthHistory',
    value: 'Birth History',
    label: 'Birth History',
    class: 'check',
  },
  {
    id: 'charCheckbox5',
    name: 'surgicalHistory',
    value: 'Surgical History',
    label: 'Surgical History',
    class: 'check',
  },
  {
    id: 'charCheckbox6',
    name: 'socialHistory',
    value: 'Social history',
    label: 'Social history',
    class: 'check',
  },
];

const imaging = [
  {
    id: 'Plain radiograph',
    name: 'plainRadiograph',
    value: 'Plain radiograph',
    label: 'Plain radiograph',
    class: 'check',
  },
  {
    id: 'Ultrasound',
    name: 'ultrasound',
    value: 'Ultrasound',
    label: 'Ultrasound',
    class: 'check',
  },
  {
    id: 'CT',
    name: 'ct',
    value: 'CT',
    label: 'CT',
    class: 'check',
  },
  {
    id: 'MRI',
    name: 'mri',
    value: 'MRI',
    label: 'MRI',
    class: 'check',
  },
  {
    id: 'Nuclear Medicine',
    name: 'nuclearMedicine',
    value: 'Nuclear Medicine',
    label: 'Nuclear Medicine',
    class: 'check',
  },
  {
    id: 'EKG',
    name: 'ekg',
    value: 'EKG',
    label: 'EKG',
    class: 'check',
  },
];

const documentType = [
  {
    id: 'Discharge Notes',
    name: 'dischargeNotes',
    value: 'Discharge Notes',
    label: 'Discharge Notes',
    class: 'check',
  },
  {
    id: 'History & Physical Notes',
    name: 'historyAndPhysicalNotes',
    value: 'History & Physical Notes',
    label: 'History & Physical Notes',
    class: 'check',
  },
  {
    id: 'Progress Notes',
    name: 'progressNotes',
    value: 'Progress Notes',
    label: 'Progress Notes',
    class: 'check',
  },
  {
    id: 'Procedure Notes',
    name: 'procedureNotes',
    value: 'Procedure Notes',
    label: 'Procedure Notes',
    class: 'check',
  },
  {
    id: 'Social Work',
    name: 'socialWork',
    value: 'Social Work',
    label: 'Social Work',
    class: 'check',
  },
  {
    id: 'Admission Notes',
    name: 'admissionNotes',
    value: 'Admission Notes',
    label: 'Admission Notes',
    class: 'check',
  },
  {
    id: 'Pre-operative Notes',
    name: 'preOperativeNotes',
    value: 'Pre-operative Notes',
    label: 'Pre-operative Notes',
    class: 'check',
  },
  {
    id: 'Operative Notes',
    name: 'operativeNotes',
    value: 'Operative Notes',
    label: 'Operative Notes',
    class: 'check',
  },
  {
    id: 'Anesthesia Notes',
    name: 'anesthesiaNotes',
    value: 'Anesthesia Notes',
    label: 'Anesthesia Notes',
    class: 'check',
  },
];

const systemEntries = [
  {
    id: 'Admission time',
    name: 'admissionTime',
    value: 'Admission time',
    label: 'Admission time',
    data_name: 'Inpatient',
    class: 'check',
  },
  {
    id: 'Doctor assigned time',
    name: 'doctorAssignedTime',
    value: 'Doctor assigned time',
    label: 'Doctor assigned time',
    data_name: 'Doctor assigned time',
    class: 'check',
  },
  {
    id: 'Doctor start note',
    name: 'doctorStartNote',
    value: 'Doctor start note',
    label: 'Doctor start note',
    data_name: 'Doctor start note',
    class: 'check',
  },
  {
    id: 'Doctor signed note',
    name: 'doctorSignedNote',
    value: 'Doctor signed note',
    label: 'Doctor signed note',
    data_name: 'Doctor signed note',
    class: 'check',
  },
  {
    id: 'Doctor signed order',
    name: 'doctorSignedOrder',
    value: 'Doctor signed order',
    label: 'Doctor signed order',
    data_name: 'Doctor signed order',
    class: 'check',
  },
  {
    id: 'Doctor changed order',
    name: 'doctorChangedOrder',
    value: 'Doctor changed order',
    label: 'Doctor changed order',
    data_name: 'Doctor changed order',
    class: 'check',
  },
  {
    id: 'Discharge order',
    name: 'dischargeOrder',
    value: 'Discharge order',
    label: 'Discharge order',
    data_name: 'Discharge order',
    class: 'check',
  },
  {
    id: 'Discharge time',
    name: 'dischargeTime',
    value: 'Discharge time',
    label: 'Discharge time',
    data_name: 'Outpatient',
    class: 'check',
  },
  {
    id: 'Nurse assigned time',
    name: 'nurseAssignedTime',
    value: 'Nurse assigned time',
    label: 'Nurse assigned time',
    data_name: 'Nurse assigned time',
    class: 'check',
  },
  {
    id: 'Nurse start note',
    name: 'nurseStartNote',
    value: 'Nurse start note',
    label: 'Nurse start note',
    data_name: 'Nurse start note',
    class: 'check',
  },
  {
    id: 'Nurse signed note',
    name: 'nurseSignedNote',
    value: 'Nurse signed note',
    label: 'Nurse signed note',
    data_name: 'Nurse signed note',
    class: 'check',
  },
  {
    id: 'Nurse viewed order',
    name: 'nurseViewedOrder',
    value: 'Nurse viewed order',
    label: 'Nurse viewed order',
    data_name: 'Nurse viewed order',
    class: 'check',
  },
  {
    id: 'Order complete',
    name: 'orderComplete',
    value: 'Order complete',
    label: 'Order complete',
    data_name: 'Order complete',
    class: 'check',
  },
  {
    id: 'Medication given',
    name: 'systemMedicationGiven',
    value: 'Medication given',
    label: 'Medication given',
    data_name: 'Medication given',
    class: 'check',
  },
  {
    id: 'Dose',
    name: 'systemDose',
    value: 'Dose',
    label: 'Dose',
    data_name: 'Dose',
    class: 'check',
  },
  {
    id: 'Labs',
    name: 'labs',
    value: 'Labs',
    label: 'Labs',
    data_name: 'Labs',
    class: 'check',
  },
];
const vitalCheckbox = [
  {
    heartRate: [
      { id: 'heartRateSelectAll', value: 'All', label: 'All', class: 'check' },
      {
        id: 'heart_2',
        value: 'Lowest',
        label: 'Lowest',
        class: 'heartRateCheckbox check',
      },
      {
        id: 'heart_3',
        value: 'Highest',
        label: 'Highest',
        class: 'heartRateCheckbox check',
      },
    ],
    bloodPessure: [
      {
        id: 'bloodPessureSelectAll',
        value: 'All',
        label: 'All',
        class: 'check',
      },
      {
        id: 'bp_2',
        value: 'Systolic',
        label: 'Systolic',
        class: 'bloodPessureCheckbox check',
      },
      {
        id: 'bp_3',
        value: 'Diastolic',
        label: 'Diastolic',
        class: 'bloodPessureCheckbox check',
      },
    ],
    meanArterial: [
      {
        id: 'meanArterialSelectAll',
        value: 'All',
        label: 'All',
        class: 'check',
      },
      {
        id: 'mean_2',
        value: 'Min',
        label: 'Min',
        class: 'meanArterialCheckBox check',
      },
      {
        id: 'mean_3',
        value: 'Max',
        label: 'Max',
        class: 'meanArterialCheckBox check',
      },
    ],
    respiratoryRate: [
      {
        id: 'respiratoryRateSelectAll',
        value: 'All',
        label: 'All',
        class: 'check',
      },
      {
        id: 'rate_2',
        value: 'Min',
        label: 'Min',
        class: 'respiratoryRateCheckbox check',
      },
      {
        id: 'rate_3',
        value: 'Max',
        label: 'Max',
        class: 'respiratoryRateCheckbox check',
      },
    ],
    o2Saturation: [
      {
        id: 'o2SaturationSelectAll',
        value: 'All',
        label: 'All',
        class: 'check',
      },
      {
        id: 'o2_2',
        value: 'Min',
        label: 'Min',
        class: 'o2SaturationCheckbox check',
      },
      {
        id: 'o2_3',
        value: 'Max',
        label: 'Max',
        class: 'o2SaturationCheckbox check',
      },
    ],
  },
];

export { charCheckbox, vitalCheckbox, imaging, systemEntries, documentType };
